environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -q

build_script:
  - npm run build
  - rm -r node_modules/
  - npm install -q --production
  - npm test
