image: node:6-alpine

before_script:
 - npm set registry $NPM_REGISTRY

build:
  stage: build
  script:
   - npm install -q
   - npm run build
  artifacts:
    expire_in: 31d
    paths:
     - dist/

test:
  stage: test
  dependencies: 
   - build
  script:
   - npm install -q --production
   - npm test
