image: node:4

before_script:
 - npm set registry $NPM_REGISTRY

build:
  script:
   - npm install -q
   - npm run build
  artifacts:
    expire_in: 31d
    paths:
     - dist/

test:
  dependencies: build
  script:
   - npm install -q --production
   - npm test
